<?xml version="1.0" encoding="utf-8"?><Database Name="NDYDUC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-58LSI00;Initial Catalog=NDYDUC;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Group_5.Properties.Settings" SettingsPropertyName="NDYDUCConnectionString" Provider="System.Data.SqlClient" />
</Database>